# run with: docker compose --env-file .env -f deployments/docker/docker-compose.yml up --build -d

services:
  postgres:
    image: postgres:17-alpine
    container_name: postgres
    expose:
      - "5432"
    env_file:
      - ../../.env
    environment:
      POSTGRES_DB: mosaic
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:8-alpine
    container_name: redis
    expose:
      - "6379"
    env_file:
      - ../../.env
    command:
      [
        "redis-server",
        "--requirepass",
        "${REDIS_PASSWORD}",
        "--appendonly",
        "yes",
      ]
    volumes:
      - redis_data:/data

  minio:
    image: minio/minio:latest
    container_name: minio
    expose:
      - "9000"
      - "9001"
    env_file:
      - ../../.env
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      MINIO_BROWSER_REDIRECT_URL: ${MINIO_BROWSER_REDIRECT_URL}
      MINIO_CONSOLE_ADDRESS: ":9001"
      MINIO_ADDRESS: ":9000"
      MINIO_CONSOLE_SECURE_TLS_REDIRECT: "off"
      MINIO_BROWSER_REDIRECT: "off"
      MINIO_SITE_REPLICATION_ENABLED: ${MINIO_SITE_REPLICATION_ENABLED}
    command: server /data --address ":9000" --console-address ":9001"
    volumes:
      - minio_data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 5s
      timeout: 3s
      retries: 30

  minio-init:
    image: minio/mc:latest
    container_name: minio-init
    depends_on:
      minio:
        condition: service_healthy
    entrypoint: >
      /bin/sh -c "
      until /usr/bin/mc alias set myminio http://minio:9000 admin ${MINIO_ROOT_PASSWORD}; do sleep 2; done;
      /usr/bin/mc mb myminio/${MINIO_IMAGE_BUCKET} --ignore-existing;
      /usr/bin/mc mb myminio/${MINIO_LOGOS_BUCKET} --ignore-existing;
      /usr/bin/mc mb myminio/${MINIO_CHAT_BUCKET} --ignore-existing;
      /usr/bin/mc mb myminio/${MINIO_PREVIEW_BUCKET} --ignore-existing;
      /usr/bin/mc anonymous set public myminio/${MINIO_IMAGE_BUCKET};
      /usr/bin/mc anonymous set public myminio/${MINIO_LOGOS_BUCKET};
      /usr/bin/mc anonymous set public myminio/${MINIO_CHAT_BUCKET};
      /usr/bin/mc anonymous set public myminio/${MINIO_PREVIEW_BUCKET};
      echo 'Buckets initialized successfully';
      exit 0;
      "
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
      - MINIO_IMAGE_BUCKET=${MINIO_IMAGE_BUCKET}
      - MINIO_LOGOS_BUCKET=${MINIO_LOGOS_BUCKET}
      - MINIO_CHAT_BUCKET=${MINIO_CHAT_BUCKET}
      - MINIO_PREVIEW_BUCKET=${MINIO_PREVIEW_BUCKET}
    restart: "no"

  backend:
    build:
      context: ../../backend
      dockerfile: Dockerfile
      args:
        - BUILDKIT_INLINE_CACHE=1
    container_name: backend
    depends_on:
      postgres:
        condition: service_started
      redis:
        condition: service_started
      minio:
        condition: service_healthy
      minio-init:
        condition: service_completed_successfully
    expose:
      - "8080"
      - "8091"
    env_file:
      - ../../.env
    environment:
      ENVIRONMENT: production
      ENV_FILE: /dev/null
      DATABASE_URL: postgres://postgres:${POSTGRES_PASSWORD}@postgres:5432/mosaic?sslmode=disable
      REDIS_URL: redis://:${REDIS_PASSWORD}@redis:6379
      MINIO_ENDPOINT: ${MINIO_ENDPOINT}
      MINIO_PUBLIC_URL: ${MINIO_PUBLIC_URL}
      SERVER_PORT: 8080
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      MINIO_IMAGE_BUCKET: ${MINIO_IMAGE_BUCKET}
      MINIO_LOGOS_BUCKET: ${MINIO_LOGOS_BUCKET}
      MINIO_CHAT_BUCKET: ${MINIO_CHAT_BUCKET}
      MINIO_PREVIEW_BUCKET: ${MINIO_PREVIEW_BUCKET}
      MINIO_USE_SSL: "false"
      MINIO_REGION: "us-east-1"
      STABLE_DIFFUSION_URL: ${STABLE_DIFFUSION_URL}
      FRONTEND_URL: ${FRONTEND_URL}
      RECAPTCHA_SITE_KEY: ${RECAPTCHA_SITE_KEY}
      RECAPTCHA_SECRET_KEY: ${RECAPTCHA_SECRET_KEY}
      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_USERNAME: ${SMTP_USERNAME}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
      SMTP_FROM: ${SMTP_FROM}
      SMTP_SSL: ${SMTP_SSL}
      ALFA_BANK_PROD_URL: ${ALFA_BANK_PROD_URL}
      ALFA_BANK_USERNAME: ${ALFA_BANK_USERNAME}
      ALFA_BANK_PASSWORD: ${ALFA_BANK_PASSWORD}
      ALFA_BANK_WEBHOOK_SECRET: ${ALFA_BANK_WEBHOOK_SECRET}
      ALFA_BANK_WEBHOOK_URL: ${ALFA_BANK_WEBHOOK_URL}
      LETSENCRYPT_DOMAIN: ${LETSENCRYPT_DOMAIN}
      LETSENCRYPT_EMAIL: ${SMTP_FROM}
      ACCESS_TOKEN_SECRET: ${ACCESS_TOKEN_SECRET}
      REFRESH_TOKEN_SECRET: ${REFRESH_TOKEN_SECRET}
      DEFAULT_ADMIN_PASSWORD: ${DEFAULT_ADMIN_PASSWORD}
      DEFAULT_ADMIN_EMAIL: ${DEFAULT_ADMIN_EMAIL}
      DEFAULT_PASSWORD: ${DEFAULT_PASSWORD}
      IMAGE_LOCAL_RETENTION_HOURS: "24"
      GITLAB_BASE_URL: ${GITLAB_BASE_URL}
      GITLAB_API_TOKEN: ${GITLAB_API_TOKEN}
      GITLAB_PROJECT_ID: ${GITLAB_PROJECT_ID}
    volumes:
      - backend_temp:/tmp
      - ../../backend/scripts/pallete_bw.xlsx:/app/scripts/pallete_bw.xlsx:ro
      - ../../backend/scripts/pallete_fl.xlsx:/app/scripts/pallete_fl.xlsx:ro
      - ../../backend/scripts/pallete_tl.xlsx:/app/scripts/pallete_tl.xlsx:ro
      - ../../backend/scripts/pallete_max.xlsx:/app/scripts/pallete_max.xlsx:ro
    restart: unless-stopped

  dashboards:
    build:
      context: ../../frontend/dashboards
      dockerfile: Dockerfile
      target: nginx
      args:
        BUILD_ENV: prod
        REACT_APP_API_BASE_URL: ${REACT_APP_API_BASE_URL}
        REACT_APP_ENVIRONMENT: ${REACT_APP_ENVIRONMENT}
        REACT_APP_DASHBOARD_URL: ${REACT_APP_DASHBOARD_URL}
        REACT_APP_PUBLIC_SITE_URL: ${REACT_APP_PUBLIC_SITE_URL}
        REACT_APP_API_URL: ${REACT_APP_API_BASE_URL}
        REACT_APP_DEBUG: "false"
    container_name: dashboards
    expose:
      - "80"
    depends_on:
      - backend
    restart: unless-stopped

  public-site:
    build:
      context: ../../frontend/public-site
      dockerfile: Dockerfile
      target: nginx
      args:
        BUILD_ENV: prod
    container_name: public-site
    expose:
      - "80"
    environment:
      VITE_API_BASE_URL: ${VITE_API_BASE_URL}
      VITE_ENVIRONMENT: ${VITE_ENVIRONMENT}
      VITE_DASHBOARD_URL: ${VITE_DASHBOARD_URL}
      VITE_PUBLIC_SITE_URL: ${VITE_PUBLIC_SITE_URL}
    depends_on:
      - backend
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    expose:
      - "3000"
    env_file:
      - ../../.env
    environment:
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_ADMIN_PASSWORD}
      GF_USERS_ALLOW_SIGN_UP: ${GRAFANA_ALLOW_SIGN_UP}
      GF_SECURITY_ADMIN_USER: ${GRAFANA_ADMIN_USER}
      GF_SERVER_ROOT_URL: ${GRAFANA_SERVER_ROOT_URL}
      GF_SERVER_SERVE_FROM_SUB_PATH: true
      GF_SECURITY_COOKIE_SECURE: false
      GF_SECURITY_COOKIE_SAMESITE: lax
      GF_SERVER_HTTP_PORT: 3000
      GF_SERVER_PROTOCOL: http
      GF_SECURITY_DISABLE_GRAVATAR: true
      GF_SECURITY_COOKIE_REMEMBER_NAME: grafana_remember
    volumes:
      - grafana_data:/var/lib/grafana
      - ../../monitoring/grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards:ro
      - ../../monitoring/grafana/provisioning/datasources/datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml:ro
      - ../../monitoring/grafana/dashboards:/var/lib/grafana/dashboards:ro
    depends_on:
      - prometheus
      - loki

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    expose:
      - "9090"
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.enable-lifecycle"
      - "--web.listen-address=0.0.0.0:9090"
    volumes:
      - ../../monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus

  loki:
    image: grafana/loki:latest
    container_name: loki
    expose:
      - "3100"
    command:
      [
        "-config.file=/etc/loki/local-config.yaml",
        "-server.http-listen-port=3100",
      ]
    volumes:
      - ../../monitoring/loki.yml:/etc/loki/local-config.yaml:ro
      - loki_data:/loki

  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    command: ["-config.file=/etc/promtail/config.yml"]
    volumes:
      - ../../monitoring/promtail.yml:/etc/promtail/config.yml:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/log:/var/log:ro
    depends_on:
      - loki

  nginx:
    image: nginx:1.29.1-alpine
    container_name: nginx
    depends_on:
      - backend
      - public-site
      - dashboards
      - minio
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ../nginx/production.conf:/etc/nginx/nginx.conf:ro
      - /etc/nginx/conf.d:/etc/nginx/conf.d:rw
      - certbot_www:/var/www/certbot
      - /etc/letsencrypt:/etc/letsencrypt:ro
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:
  minio_data:
  backend_temp:
  grafana_data:
  prometheus_data:
  loki_data:
  certbot_www: